### ISSUE TITLE
Error en los links del nav llama el Controller de devise.

### ISSUE THREAD

**Issue by Frank004** [rubyespanol/Primer_Blog#23]
Started GET "/users/sign_in" for ::1 at 2016-01-23 01:24:13 -0400
      Processing by Devise::SessionsController#new as HTML
        Rendered devise/shared/_links.html.erb (0.2ms)
    
Error en los links del nav cuando le das a sign_in o log_in.
No se si ya notaron este error. voy a verificarlo y subo un PR.

    Rendered devise/sessions/new.html.erb within layouts/application (2.3ms)
        Rendered layouts/_navbar.html.erb (2.1ms)
      Completed 500 Internal Server Error in 54ms (ActiveRecord: 0.0ms)

      ActionView::Template::Error (No route matches {:action=>"home", :controller=>"devise/pages"}):
          15:     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          16:       <ul class="nav navbar-nav navbar-right">
          17:         <li class="nav-links">
          18:           <%= link_to "Inicio", controller: "pages", action: "home" %>
          19:           <%= link_to "Nosotros", controller: "pages", action: "about" %>
          20:           <%= link_to "Contacto", controller: "pages", action: "contact" %>
          21:         </li>
        app/views/layouts/_navbar.html.erb:18:in `_app_views_layouts__navbar_html_erb___3547307104779791340_70117384510000'
        app/views/layouts/application.html.erb:16:in `_app_views_layouts_application_html_erb___3653701967076004921_70117360911760'

**Comment by Frank004** [comment]
Listo

*ANTES*

        <li class="nav-links">
          <%= link_to "Inicio", controller: "pages", action: "home" %>
          <%= link_to "Nosotros", controller: "pages", action: "about" %>
          <%= link_to "Contacto", controller: "pages", action: "contact" %>
        </li>

*DESPUES*

        <li class="nav-links">
          <%= link_to "Inicio", home_path %>
          <%= link_to "Nosotros", about_path %>
          <%= link_to "Contacto", contact_path %>
        </li>

**Comment by oviewz** [comment]
ya estaba modificado...

**Comment by Frank004** [comment]
@oviewz  en cual estaba pq baje el repo de dev que es el que se esta trabajando y no estaba. al menos que este en el master??

**Comment by Frank004** [comment]
@oviewz  ya lo encontre.

https://github.com/rubyespanol/Primer_Blog/commit/0ff0b7b933456b40877a97061a99736cd7b2bb93#diff-bd5fbcdc8c1d642e80e90ed8b43fb1b5L8
