### ISSUE TITLE
Testing con Rspec y Capybara, no hacer PR en código sin testear

### ISSUE THREAD

**Issue by ssoulless** [rubyespanol/Primer_Blog#24]
Hola, veo que están montando el código y no están escribiendo tests. propongo que se aplique RSpec con Capybara para el testing, y que se utilice Travis CI como herramienta de integración continua, de esa manera los PR tienen que pasar los tests antes de acer merge al repo.

**Comment by Frank004** [comment]
Saludos @ssoulless  yo quiero aprender a hacer estos test. si quieres crea un pr con el setup y escribe aqui la guia o pasos a seguir para que los que no saben hacer test podamos guiarnos de ustedes.

**Comment by ssoulless** [comment]
Vale, voy a esperar hasta mañana a ver si alguien tiene sugerencias con respecto al testing del proyecto, sino entonces subo una estructura acá en este Thread y comenzamos en el PR

**Comment by Frank004** [comment]
@ssoulless  si tienes el tiempo para trabajar esa parte nos dejas saber, para poner esto en marcha. ya que como tal lo unico que se a creando es el setup basico. nada de metodos y routes complicados. solo html scss y un par de controllers.

**Comment by ssoulless** [comment]
Ok perfecto entonces estamos en el momento adecuado para comenzar el Testing.

**Comment by Frank004** [comment]
@ssoulless  si ya lo habíamos discutido lo que no sabíamos era con que herramienta. verifica en las gemas y en la estructura de test que creo que se monto algo pero mi conocimiento es mínimo en test.

**Comment by ssoulless** [comment]
No estoy revisando y en #1 no se ha definido aún, esperemos hasta mañana a ver si alguien más se une a la discusión.

**Comment by gbarzola** [comment]
A mi me gustaria aprender a realizar testing, con la guia de @ssoulless  podemos lograr buenos avances :+1:

**Comment by Frank004** [comment]
:+1:  en acuerdo con @ssoulless  y @gbarzola

**Comment by lesm** [comment]
Concuerdo con usar RSpec con Capybara @ssoulless

**Comment by nmenag** [comment]
Un libro interesante https://leanpub.com/everydayrailsrspec

**Comment by huascar** [comment]
Hola, por favor, si van a trabajar con Rspec, eliminen toda la carpeta test, no sirve. Otro para realizar unit testing Rspec, y en caso de necesitarse para test integration Capybara. Pero lo importante es por favor ver el tema de Rspec. tanto para validaciones, métodos y funciones q se van a crear, tanto para modelos y controladores

**Comment by huascar** [comment]
Para usar datos de prueba incluyan la gema "faker" para tener datos de pruebas y poblar la base. otro para el Rsepc es una buena combinacion usar el factory_girl.

**Comment by Frank004** [comment]
@huascar faker estoy familiarizado  en factory_girl no tanto sera una buena tarea. :+1:

**Comment by Frank004** [comment]
@ssoulless  y @FMauricioS como vamos con esta integración.

**Comment by ssoulless** [comment]
@Frank004  Hoy hago mi PR

**Comment by Frank004** [comment]
@ssoulless  perfecto so esperamos por el para poder trabajar

**Comment by roadev** [comment]
Genial @ssoulless

**Comment by ssoulless** [comment]
Ya está el PR que define el testing. Quedó con RSpec y Capybara para tests de aceptación, la estructura de folders y las instrucciones junto con algunos ejemplo las pueden ver en #39.

Allí hay algunas sugerencias para el admin del repo para que implemente Travis CI y Coveralls.
