### ISSUE TITLE
Versionamiento del proyecto

### ISSUE THREAD

**Issue by ssoulless** [rubyespanol/Primer_Blog#26]
Creo que sería buena idea manejar Versionamiento para el proyecto, un archivo changelog donde cada que se le haga un merge a master se le coloque los cambios de versión a versión, yo voy a proponer un formato para este archivo pronto. El Estándar de versionamiento propongo que usemos el más conocido [Semantic Versioning](http://semver.org)

Los siguientes PR que voy a hacer los voy a hacer siguiendo estos estándares si alguien tiene una mejor idea puede proponer.

**Comment by gbarzola** [comment]
Genial, necesitamos trabajar con estándares :+1:

**Comment by Frank004** [comment]
@ssoulless  muy de acuerdo. otra tarea que puede ir trabajando.

**Comment by Frank004** [comment]
@ssoulless @gbarzola  tiene un tutorial del tema para ponerlo en la pagina principal con lo de capy también para cuando los nuevos entren tengan esta info. igual agregar al #1

**Comment by Frank004** [comment]
si entienden ingles https://www.youtube.com/watch?v=QMUSkra7Blk

**Comment by roadev** [comment]
Les comparto :)
https://github.com/skywinder/github-changelog-generator

**Comment by ssoulless** [comment]
Ya quedó definido el tema de versionamiento, también ya se definió la estructura del CHANGELOG, para más detalles ver #39
