### ISSUE TITLE
Usar .gitignore

### ISSUE THREAD

**Issue by huascar** [rubyespanol/Primer_Blog#30]
Hola, por favor deben usar el archivo .gitignore para "ignorar" archivos que cada uno trabaja localmente en su equipo como archivos de configuración  y no deberían subir en los commits. 

Por ejemplo en el caso de usarse un adaptador diferente al sqlite3 y quiera levantarse en producción una vez terminado, o por el mismo hecho de hacer test es probable que se use otro adaptador de base de datos.

Regularmente el uso de este archivo impide que se suban al repositorio: el database.yml ya que este puede ser diferente para cada uso.

Otro los archivos del deploy en caso de usarse Capistrano.
Otros archivos y carpetas que se usa en cada editor de código/ IDE, Vim, Rubymine, SublimeText, Atom, VSCode.
Otro la parte de los versionamientos, no todos estan usando RVM otros quieren usar Rbenv, y quizá no todos usan la misma version de ruby, ignorar el .ruby-version y el ruby-gemset en caso de usarse RVM.
 
Por ejemplo el archivo .gitignore deberia tener: 

## Ignore bundler config.
/.bundle

## Ignore the default SQLite database.
/db/*.sqlite3
/db/*.sqlite3-journal

## Ignore all logfiles and tempfiles.
/log/*
!/log/.keep
/tmp
.ruby-version
.ruby-gemset
.idea/*
config/database.yml
deploy/*

NOTA: Para ignorar ciertos archivos o carpetas deben eliminarlas de su equipo local, y luego commitearlas en el branch de trabajo (NO MASTER). MASTER deberia no incluir cambios hasta el despliegue de la app.

Para el caso de que necesiten incluir una configuracion del database.yml, incluyan la configuracion de al menos 2, Mysql, Postgresql y Sqlite. Por ejemplo, database.yml.mysql | database.yml.postgres. 
Para que cada uno se configure.

**Comment by Frank004** [comment]
@huascar me interesa hacer esto en mi equipo local.

**Comment by roadev** [comment]
Listo.
@huascar: ¿Puedes crear ese .gitignore? Nosotros podemos aportar en cómo más complementarlo.

**Comment by huascar** [comment]
ok, pero no hare ningun cambio hasta q este ordenado y solo tengamos dos branches. master y dev (creo q es asi como lo estan trabajando ) y dev este todo lo q se ha trabajado. Por que si no todos vamos a entrar en conflictos..

Saludos

**Comment by Frank004** [comment]
@huascar  agregue al .gitignore: 

      .ruby-version
      .ruby-gemset

**Comment by Writkas** [comment]
También hay que ignorar el archivo .DS_Store y el .directory que generan algunos sistemas operativos

**Comment by Frank004** [comment]
@Writkas  puedes hacer un pr con eso.

**Comment by Writkas** [comment]
@Frank004 bueno
