### ISSUE TITLE
NO se trabaja en MASTER

### ISSUE THREAD

**Issue by huascar** [rubyespanol/Primer_Blog#31]
Hola, el branch MASTER solo debería servir para:

Una vez que se tenga una estructura base, crear otro branch develop de master y trabajar ahí todo lo que se deba hacer, hasta el momento del merging una vez que se termine la app y se levante para producción.

**Comment by Frank004** [comment]
muy de acuerdo con tigo.

**Comment by roadev** [comment]
Fue lo que dije antes de siquiera comenzar el proyecto :p
La rama que creé se llama dev, voy a actualizarla
Master debe ser la estable ya para staging...

**Comment by huascar** [comment]
Entonces por favor coordinen para hacer el merging. y dejen solo dos branches, master y dev. y de dev saquen otros branches si fuese necesario. y lo eliminan cuando terminen para no estar con branches colgados q estan desactualizados.

**Comment by roadev** [comment]
Hecho

**Comment by roadev** [comment]
Hecho
