### ISSUE TITLE
Eliminación lista de desarrolladores

### ISSUE THREAD

**Issue by roadev** [rubyespanol/Primer_Blog#5]
¿Eliminamos la lista de desarrolladores?
Se pueden ver en https://github.com/rubyespanol/Primer_Blog/graphs/contributors
Igual conozco muchos proyectos que mantienen una lista en el README...

**Comment by Oxyrus** [comment]
Yo la elimine en #4 , no sé que opinen

**Comment by Frank004** [comment]
no problema

**Comment by roadev** [comment]
Yo creo que definitivamente sí dejamos la lista, antes completémosla xD
