### ISSUE TITLE
Data model

### ISSUE THREAD

**Issue by gbarzola** [rubyespanol/Primer_Blog#9]
Definamos la estructura del blog :+1:

**Comment by Oxyrus** [comment]
¿Qué tan complejo queremos que sea?

Es decir, que tenga categorías, tags, comentarios, depende de que busquemos crear.

**Comment by gbarzola** [comment]
Controladores:
Post
Comments

Modelos:
Comment
Post
User

Controladores:
Posts
Comments
Pages

Vistas:
Comments
Devise
Layouts
Pages
Posts

**Comment by Frank004** [comment]
Debe tener  
Models:
Usuarios
Role
Profile
Media (imagenes opcional)

**Comment by Oxyrus** [comment]
@Frank004 pero el Profile lo podemos crear con el modelo de usuario, simplemente con un controlador y las vistas

**Comment by ssoulless** [comment]
Hola, me gustaría aportar con el tema de roles, podemos usar la gema https://github.com/RolifyCommunity/rolify junto con https://github.com/CanCanCommunity/cancancan yo me encargaría de crear el sistema de roles y permisos, crearía también una vista para que los admins asignen roles. Creo que la estructura que plantean está bien.

Para poder proceder necesitaré que esté lista la integración con devise.

**Comment by Oxyrus** [comment]
De lo que no estoy seguro es si sea necesario añadir roles, es decir ¿cuáles necesitaríamos?

**Comment by Frank004** [comment]
@Oxyrus para los roles necesitamos Editore, Admin, User solamente.
para lo del perfile todo depende de que quieres logra podemos usar un controller y poner la info de perfil en la tabla de user y no tenemos problema alguno. Si queremos hacer algo mas complejo con los Users pues yo recomiendo una tabla externa para eso.

**Comment by Oxyrus** [comment]
De ser ese el caso pues veo bien la integración de Rolify

**Comment by Frank004** [comment]
@Oxyrus  que tal si dejamos el perfil dentro del user a lo que trabajamos y si se ve la necesidad lo exportamos a una tabla aparte?

**Comment by Oxyrus** [comment]
Si, me parece innecesario crear otra tabla para el perfil aún @Frank004

**Comment by Frank004** [comment]
Modelos:
Comment
Post
User
Tags
Category

Controladores:
Posts
Comments
Pages
Users
Dashboards o ControlPanel  "para el admin" *esto se puede crear y mas adelante se trabaja

Vistas:
Comments
Devise
Layouts
Pages
Posts
Users
Dashboards

**Comment by ssoulless** [comment]
Concuerdo que es innecesario crear otro modelo para el perfil, en la misma tabla del usuario se puede guardar esa información, Tal vez en algunos casos haya que crear modelos auxiliares, para cierto tipo de información del perfil.

Con respecto a si integrar Rolify o no, creo que por salud del proyecto y escalabilidad es la mejor práctica. No sabemos hasta donde escale el proyecto y es mejor empezar bien desde el comienzo.

**Comment by gbrlmrllo** [comment]
### Models

Tag
Post
User
Category
Subcategory
Comment

**Comment by Frank004** [comment]
Modelos:
		Comment
			description	:text
			post_id		:integer
			user_id		:integer
			approval	:boolean

		Post
			tittle		:string
			description	:text
			user_id		:integer
			draft		:boolean

		User
			username	:string  
			first_name	:string
			last_name	:string
			email		:string

		Tags
			name		:string

		Category
			name		:string

	//////////////Tablas para el many to many//////////////////

		PostTag
			post_id		:integer
			tag_id		:integer

		PostCategory
			post_id		:integer
			category_id	:integer

**Comment by gbrlmrllo** [comment]
Creo que para los tags podemos usar esta gema, https://github.com/mbleigh/acts-as-taggable-on

**Comment by gbarzola** [comment]
con Devise ya se tiene la estructura del User tambien

**Comment by Frank004** [comment]
@gbrlmrllo muy bien yo sugiero el tratar de usar las menos gemas posibles para el beneficio de aprender. debemos ver que gema nos facilita unas partes básicas.

**Comment by Frank004** [comment]
@gbarzola  si solo estoy haciendo la estructura DM para entender que estamos trabajando aunque una gema nos cree las tablas es una buena practica crear el DM con eso incluido

**Comment by Frank004** [comment]
@gbarzola sugiero solo añadir una migración para first y last name.

**Comment by gbarzola** [comment]
Okey seria  algo como : 

rails g migration add_first_name_to_user first_name:string
rails g migration add_last_name_to_user last_name:string

**Comment by Frank004** [comment]
@gbarzola creo que lo puedes hacer en una misma migración 
   
    rails g migration add_first_and_last_name_to_user first_name:string last_name:string

**Comment by gbarzola** [comment]
okas @Frank004,  el draft para que nos serviria??

**Comment by Frank004** [comment]
@gbarzola  me estoy dejando llevar por lo mas común en un blog el draft nos sirve par cuando un editor esta creando el post pero de momento no tiene toda la información puede guardar lo como draft no va a estar publico pero se crea. cuando el regresa lo puede publicar. Podemos cambiar el nombre a status  para que de esa manera puedas usar Y/N como Publicado/Borrador

**Comment by gbarzola** [comment]
Aya que buena, buena idea !!!

**Comment by roadev** [comment]
draft como un boolean?

**Comment by Frank004** [comment]
@roadev  lo podemos hacer boolean o string da lo mismo en la ejecución. el que ustedes quieran. como el post va a estar en 2 estados Publico o Borrador

**Comment by roadev** [comment]
Si sólo lleva dos estados sería mucho más conveniente un boolean, opino yo @Frank004 
True: Publicado
False: Draft

**Comment by Frank004** [comment]
@gbarzola ya actualice de nuevo. verifica.  Necesito que me des un poco de luz con la gema que van a usar para los Roles 

@roadev claro por eso doy las 2 opciones.

**Comment by gbarzola** [comment]
@Frank004  las tablas many to many en que nos benefician?

**Comment by Frank004** [comment]
@gbarzola está para un Post puede tener mucho tags y Muchas categorías y los mismo para las categorías y Tags.

podemos o utilizar esa técnica o podemos hacer el :has_and_belongs_to_many

**Comment by Writkas** [comment]
pero cual seria la diferencia ?? ando pregunton hoy xD

**Comment by Frank004** [comment]
@Writkas   ajajaj  yo de explicador jajajaaj eso es bueno vamos aprendiendo uno del otro.
la que tiene las tablas 
    PostTag
        post_id     :integer
        tag_id      :integer

    PostCategory
        post_id     :integer
        category_id :integer

contienes ID la tabla y se puede implementar alguna otra column que necesites. en esta puedes usar el nombre que tu quieras para la tabla.

con el :has_and_belongs_to_many creas la tabla y tiene que ir a la conveción de RoR.
donde el nombre de la tabla va a usar los 2 nombres de las otras 2 tablas que quieres unir y en orden alfabético. ejemplo: category_posts  en adición tienes que poner el primary_key false

**Comment by Writkas** [comment]
ahh ok gracias :+1:

**Comment by Oxyrus** [comment]
@Frank004 la gema para los roles va a ser [Rolify](https://github.com/RolifyCommunity/rolify)

**Comment by Frank004** [comment]
@Oxyrus lo que estoy buscando es que tabla crea para presentar el data model visual bien estructurado. si tienes un ejemplo de la migración que crea

**Comment by Oxyrus** [comment]
@Frank004 https://github.com/Oxyrus/forum/blob/master/db/migrate/20160119014811_rolify_create_roles.rb

**Comment by Frank004** [comment]
DataModel Columns. ahora preparo el de asociaciones.  

![screen shot 2016-01-21 at 4 38 10 pm](https://cloud.githubusercontent.com/assets/7242689/12493821/64767f28-c05d-11e5-8d16-fbd12b6f7536.jpg)

**Comment by Frank004** [comment]
Asociaciones 

![screen shot 2016-01-21 at 4 55 20 pm](https://cloud.githubusercontent.com/assets/7242689/12494323/d880f19e-c05f-11e5-8eaa-9e43de43b762.jpg)

**Comment by gbarzola** [comment]
Una obra de arte maestro!! @Frank004  bien ahi :+1:

**Comment by Writkas** [comment]
:100:

**Comment by Frank004** [comment]
ok pues solo falta crear las migraciones las posteo pronto. a trabajar en ellas.

**Comment by roadev** [comment]
@Frank004 genial ese diagrama :D
¿En qué lo hiciste?

**Comment by Frank004** [comment]
@roadev https://www.yworks.com/products/yed

**Comment by Frank004** [comment]
rails g migration add_first_name_to_user first_name:string

    rails g migration add_last_name_to_user last_name:string

    rails g model Post title:string description:text status:boolean  user:references

    rails g model Comment description:text approval:boolean user:references post:references

    rails g model Category name:string

    rails g model PostTag post:references tag:references  
    # Recuerda cambiar esta linea en la migración antes de correr la para que no tenga forem_key: 
    # create_table :posts_tags, id: false do |t|
    
    rails g model CategoryPost post:references category:references 
    # Recuerda cambiar esta linea en la migración antes de correr la para que no tenga forem_key:
    # create_table :categorys_posts, id: false do |t|

    rails g controller Comment
    rails g controller Post
    rails g controller User

**Comment by Frank004** [comment]
creo que esto puede ya cerrarse.
